apiVersion: apps/v1
kind: Deployment
metadata:
  name: healths-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healths-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: healths-app
    spec:
      containers:
        - name: healths
          image: rinatm/healths:v1
          ports:
            - name: web
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: web
            initialDelaySeconds: 20
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: web
            initialDelaySeconds: 5
            periodSeconds: 5
